version: "2.1"
services:
  gitlab-runner:
    image: ederrm/gitlab-runner:latest
    build: .
    privileged: true
    hostname: gitlab-runner
    restart: always
    volumes:
      - gitlab-runner-home:/home/gitlab-runner
      - gitlab-runner-conf:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitlab-runner-home:
  gitlab-runner-conf:
